### ISSUE TITLE
Not working with Angular.js?

### ISSUE THREAD

**Issue by F1LT3R** [ebrelsford/Leaflet.loading#20]
This is a cool addon for Leaflet!

After playing around with it using Angular.js, I could only get it to work with spinner.js using:

          var loadingControl = L.Control.loading({
              spinjs: true
          });
          map.addControl(loadingControl);

But I much prefer the image you use, and not spinner.js. I am wondering if something in Angular is tripping up the normal initialization of this control?

If you have any ideas I would be happy to poke around and create a pull request if I can get it fixed.

**Comment by ebrelsford** [comment]
@F1LT3R I'm not aware of anything Angular-specific that would stop this from working but I'd appreciate a small example if you have one.

Are you setting the CSS to make the image show up? See [the examples](http://ebrelsford.github.io/Leaflet.loading/simple.html) for details, specifically [these lines](https://github.com/ebrelsford/Leaflet.loading/blob/gh-pages/simple.html#L16-L18).

**Comment by MarkAPhillips** [comment]
Just to advise I have this working in angularjs with the default icon showing as expected.

**Comment by ebrelsford** [comment]
Thanks @MarkAPhillips, you didn't have to do anything special did you? If not I think I'll close this, but let me know.

**Comment by MarkAPhillips** [comment]
Sorry for not coming back to this earlier - I did not do anything different and had the basic functionality working with the default icon as expected. I did though later decide to change to another plugin as this worked better in the angularjs application I was creating but was more down to personal choice and also as I could not get the icon to show correctly all the time for different events.

I decided to use  http://makinacorpus.github.io/Leaflet.Spin/  which I found easier to plug in to my application

**Comment by ebrelsford** [comment]
Closing this as there doesn't seem to be anything to do from this side, please open it back up if I am wrong.
