### ISSUE TITLE
Not IE8 compatible

### ISSUE THREAD

**Issue by MatthewEdge** [ebrelsford/Leaflet.loading#23]
Minor issue: this library is not IE8 compatible because of it's use of console statements. IE8 browsers do not instantiate the console object until Developer Tools are opened. This can cause the map to break

**Comment by ebrelsford** [comment]
Good to know. I'm open to pull requests as always.

**Comment by ebrelsford** [comment]
Okay 56a0a1b should do it, @MatthewEdge, thanks again for the heads-up.

**Comment by MatthewEdge** [comment]
Cheers! :)
