### ISSUE TITLE
Will this work with google layer as well?

### ISSUE THREAD

**Issue by durga-telsiz** [ebrelsford/Leaflet.loading#24]
I am using angular-leaflet and have two layers for now. One is using google and other with OpenStreetMap. This works well with OpenStreetMap but not with google. Is there a way to make it work with google layer as well? I noticed tile 'loading' event never gets triggered for google so _handleLoading never gets executed. Is there a work around?
Thanks in advance!

**Comment by ebrelsford** [comment]
I don't use Google layers so I'm not going to be able to put the effort into fixing this. A pull request would be very welcome!

If nothing else, it would help if you could make a slimmed down example (that is, no Angular, just a simple map with a Google layer) to show that it doesn't work. If it doesn't, as [the usage notes say](https://github.com/ebrelsford/Leaflet.loading#usage), you'll need to ensure that `dataloading` and `dataload` are getting fired appropriately.
