### ISSUE TITLE
put custom spinner location

### ISSUE THREAD

**Issue by lksv** [ebrelsford/Leaflet.loading#31]
First, thanks for a perfect plugin.

I would like to put loading spinner (in my case spinjs) to custom position. E.g. make it really big in the center of the map.

Is it somehow possible through {separate: true} options and custom css? I cannot find a way:(

The only idea what I have is to change code:
- where the [spinjs is attached to DOM](https://github.com/ebrelsford/Leaflet.loading/blob/master/src/Control.Loading.js#L77-L80), to let _indicator undefined (and store _map on map).
- functions _showIndicator and hideIndicator like:
  
  ```
        _showIndicator: function() {                                       
            if (this._spinner && !this._indicator) {                       
                this._spinner.stop();                                      
                this._spinner = new Spinner(this.options.spin).spin(this._map._container);
                return;                                                    
            }
            ...
  ```

Is it reasonable solution or am I something overlooking missing?

**Comment by ebrelsford** [comment]
You should definitely be able to do this with CSS and JavaScript without changing the plugin. [Here's an example](http://jsbin.com/linawa/edit?html,output) that will need some tweaking, but it does this:

 * Set the loading indicator to have `position: absolute`
 * Use JS to set the `top` and `left` to the middle of the page. This is a rough example, but you'll want to subtract the width and height of the indicator to get it truly centered.
