### ISSUE TITLE
Endless loading with L.TileLayer.Canvas(),

### ISSUE THREAD

**Issue by rendrom** [ebrelsford/Leaflet.loading#34]
If you replace the layer `openStreetMapHumanitarian` from twobaselayers.html to L.TileLayer.Canvas(),
`openStreetMapHumanitarian = new L.TileLayer.Canvas(),`
and when you switch on this layer from layer control,  loading indicator does not stop

**Comment by ebrelsford** [comment]
Thanks for letting me know. Canvas layers don't fire `tileload` events, so I've made an exception for them here.

**Comment by rendrom** [comment]
Great! Thanks!
It may be useful to add an exception for L.GridLayer (replace L.TileLayer.Canvas in leaflet 1)?

**Comment by ebrelsford** [comment]
Thanks I've tested it but that's not an issue with Leaflet 1.0--`GridLayer` fires the events this plugin listens to appropriately.
