### ISSUE TITLE
Missing .css file in bower.json definition

### ISSUE THREAD

**Issue by magrossi** [ebrelsford/Leaflet.loading#36]
In [bower.json](https://github.com/ebrelsford/Leaflet.loading/blob/master/bower.json) it should be:
```
  "main": [
    "src/Control.Loading.css",
    "src/Control.Loading.js"
  ],
```
Instead of:
`  "main": "src/Control.Loading.js",`

**Comment by magrossi** [comment]
I created a pull request related to this.
Thanks for the great control!

**Comment by ebrelsford** [comment]
Thanks for the PR--merged. I don't currently use bower so if there are other ways to improve the `bower.json` please let me know.

**Comment by magrossi** [comment]
Thanks for the super fast response! :)
