### ISSUE TITLE
Container border on touch

### ISSUE THREAD

**Issue by torsture** [ebrelsford/Leaflet.loading#39]
Thanks for a great plugin!

I found a small problem.
When using this plugin on a touch device the border of the _container is visible as a dot when the loading indicator is hidden.

I added display none/block to the container when hiding/showing the indicator which solved the problem, but i belive this needs to be fixed in the upcomming versions.
Also fiering hide/show events would be nice.

Thanks again

**Comment by ebrelsford** [comment]
Thanks for this @torsture. Mind posting a minimal example of what you're seeing? I am having a hard time recreating it on my touch devices, so I'm wondering if there is something in your CSS that is leading to it?

**Comment by torsture** [comment]
Sorry, I should’ve been more thorough when describing the problem.
I’m using the plugin with leaflet-0.7.3 and in separate-mode, same as your separate example. I checked it out and get the same problem in the example(http://ebrelsford.github.io/Leaflet.loading/separate.html), I’ve tested with both a touchscreen laptop and my android smartphone and get the problem in both so you should be able to replicate it using your own demo.
Leaflet adds the css class “leaflet-touch” to the map container when a touch-device is running the map, I've also tried adding this class manually on nontouch  devices and get the same issue, so you can also use this to replicate the problem.

Hope this helps.

**Comment by ebrelsford** [comment]
Got it. Would you be interested in submitting a pull request? Otherwise I
should be able to get to this soon enough.

**Comment by torsture** [comment]
I'm kinda new to github so I think it's for the best if you take care of it.

**Comment by torsture** [comment]
Works like a charm, nice work thank you!
