### ISSUE TITLE
Can we show spinner while zooming?

### ISSUE THREAD

**Issue by jeevasusej** [ebrelsford/Leaflet.loading#40]
Can we show spinner while zooming?

**Comment by ebrelsford** [comment]
@jeevasusej yes, that's what the plugin does, see [the examples](http://ebrelsford.github.io/Leaflet.loading/simple.html). It shows a spinner while tiles are loading, so if you zoom in and cause more tiles to load you will see a spinner. Are you having a specific problem?

**Comment by jeevasusej** [comment]
No. Sorry I will close this issue. 

How to center the loading icon? is there any css fix?
