### ISSUE TITLE
Is there any leaflet loading version for angular 1.0

### ISSUE THREAD

**Issue by hntvip** [ebrelsford/Leaflet.loading#42]
I'm looking for spin icon , show spin icon before map load all markers. but this is use in javascript.
thanks

**Comment by ebrelsford** [comment]
I don't use Angular and don't know what it would take to make this plugin work with Angular. If you want to make a pull request I could take a look.

**Comment by ebrelsford** [comment]
Closing for now as there doesn't seem to be any further action to take, but please re-open if there is.
