### ISSUE TITLE
loadingControl doesn't exist

### ISSUE THREAD

**Issue by davetapley** [ebrelsford/Leaflet.loading#48]
The [map options](https://leafletjs.com/reference-1.7.1.html#map-option) in the Leaflet 1.7.1 docs make no mention of `loadingControl`.

**Comment by ebrelsford** [comment]
Right, Leaflet doesn't define it, that option is added by this plugin as [documented here](https://github.com/ebrelsford/Leaflet.loading#usage). You can see an example of that [here](https://github.com/ebrelsford/Leaflet.loading/blob/master/examples/leaflet-1.0/simple.html). Do you have a specific issue here?

**Comment by davetapley** [comment]
Aha, I see! Thanks for clarifying 😊 

I was _led down the garden path_ by [`react-leaflet`](https://github.com/PaulLeCam/react-leaflet), for reasons I've enumerated on https://github.com/PaulLeCam/react-leaflet/issues/847.

I think the issue needs to be resolved there, so I'll close this for now.
